import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NabBar/NavBar";

export const metadata: Metadata = {
  title: "FleaMart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NavBar/>
        <main className="container mx-auto px-2 pt-10 sm:px-3 md:px-4 lg:px-5 ">
        {children}
        </main>
      </body>
    </html>
  );
}
