import type { Metadata } from "next";
import "./globals.css";
import NavBar from "./NabBar/NavBar";
import ToasterConfig from "./toaster/Toaster";
import SignalR from "./signalr/SignalR";
import { getCurrentuser } from "./actions/AuthActions";

export const metadata: Metadata = {
  title: "FleaMart",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getCurrentuser();
  return (
    <html lang="en">
      <body>
        <ToasterConfig />
        <NavBar/>
        <main className="container mx-auto px-2 pt-10 sm:px-3 md:px-4 lg:px-5 ">
          <SignalR user={user}>
            {children}
          </SignalR>
        </main>
      </body>
    </html>
  );
}
